// ═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
// ASSETS — list of investable assets in the marketplace.
// Each asset has: id, name, category, sector, starting price, volatility, and a description shown in the asset detail modal.
// ═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════

const ASSETS = [
  { id:'ORI', name:'Orange Inc.',                category:'stock', sector:'Technology',            price:162,   volatility:0.22, desc:'Orange is a consumer technology company that designs and sells high‑end smartphones, personal computers, and wearables. Its main revenue comes from its flagship phone line, supported by a large digital ecosystem offering cloud storage, streaming, and payment services. The company sells products through its own stores, online channels, and retail partners in major global markets.' },
  { id:'KOL', name:'Cola-Kola',                  category:'stock', sector:'Food and Beverage',       price:101,   volatility:0.14, desc:'Coca Kola is a global beverage company that sells soft drinks, bottled water, juices, teas, sports drinks, and energy beverages. A large share of its revenue comes from selling concentrates, syrups, and finished drinks to bottling partners, restaurants, supermarkets, and convenience stores. Its products are distributed across many countries through a wide retail and food service network.' },
  { id:'JNJ', name:'John & Johnnie',             category:'stock', sector:'Healthcare',            price:152,   volatility:0.16, desc:'John & Johnnie is the largest healthcare company with businesses in pharmaceuticals, medical devices, and hospital supplies. It develops treatments such as cancer drugs, vaccines, immune therapies, and pain relief medicines, and also produces surgical devices, scanners, and clinical equipment. The company mainly sells to hospitals, clinics, pharmacies, and healthcare distributors.' },
  { id:'DIF', name:'Dinosaur Fuel',              category:'stock', sector:'Energy',                price:112,   volatility:0.24, desc:' Dinosaur Fuel merged with GreenLeaf Energy to form one of the largest energy companies in the market. The company explores for, produces, and refines crude oil and natural gas across several continents, with its main revenue coming from crude oil, natural gas, petrol, diesel, and related fuel products. While it has started investing in renewable energy projects, fossil fuels remain its main source of revenue.' },
  { id:'SSB', name:'SG Savings Bond',            category:'bond',  sector:'Govt',                  price:90,    volatility:0.005, desc:'Backed by the Singapore Government, Singapore Savings Bonds are a flexible and stable savings option. Bond returns are mainly driven by interest rates, government bond yields, and overall economic conditions' },
  { id:'XLK', name:'Technology ETF',             category:'Sector ETFs', sector:'Technology',      price:74,    volatility:0.15, desc: 'Technology ETF focuses on technology companies such as software developers, hardware makers and artificial intelligence. It benefits from innovation and digital adoption across the economy and is commonly used by investors looking for technology‑sector growth.' },
  { id:'RES', name:'Real Estate ETF',            category:'Sector ETFs', sector:'Real Estate',     price:40,    volatility:0.13, desc:'Real Estate ETF tracks property-related companies, including real estate investment trusts (REITs) that own and manage commercial, residential and industrial buildings. Its returns are mainly influenced rental demand, property value, interest rates, and overall economic conditions.' },
  { id:'XLV', name:'Healthcare ETF',             category:'Sector ETFs', sector:'Healthcare',      price:128,   volatility:0.12, desc:'Healthcare ETF includes companies such as pharmaceutical firms, hospitals, biotechnology companies, and medical device manufacturers. Its performance is driven by medical innovation, healthcare spending, and long-term demand for healthcare services.' },
  { id:'XLE', name:'Energy ETF',                 category:'Sector ETFs', sector:'Energy',          price:41,    volatility:0.16, desc:'Energy ETF invests in companies involved in producing and supporting oil, gas, and related services. Its performance is shaped mainly by global energy demand and commodity prices.' },
  { id:'SPY', name:'Index Funds',                category:'Index Funds',  sector:'Global',         price:135,   volatility:0.09, desc:'Index Funds represents many of the largest companies across all major industries. It invest in a broad basket of assets designed to mirror the performance of a specific benchmark index. It  giving us a low-cost, broad market exposure and diversification asset.'
 },
]; 
